import GlobalState from '@/context';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GlobalState>
          <Navbar />
          <main className='bg-white flex min-h-screen flex-col mt-[82px]'>{children}</main>
        </GlobalState>
      </body>
    </html>
  );
}
